"""Deterministic querying over analysis-ready document tables."""

from app.agent.query_engine import (
    NoMatchingRowsError,
    QueryExecutionError,
    QueryResult,
    TableQueryAgent,
    UnknownColumnError,
    UnknownTableError,
    execute_query,
)
from app.agent.natural_language import (
    AmbiguousQuestionError,
    DimensionSemantic,
    MetricSemantic,
    NaturalLanguageQueryResult,
    NaturalLanguageTableAgent,
    QuestionInterpretation,
    QuestionInterpretationError,
    SemanticCatalog,
    TotalExclusion,
    UnsupportedQuestionError,
    interpret_question,
)
from app.agent.request_parser import (
    AggregationSpec,
    FilterSpec,
    QueryRequest,
    SortSpec,
    parse_query_request,
)
from app.agent.generic_analysis import (
    apply_column_corrections,
    ask_generic_table_question,
    build_chart_data,
    build_generic_semantic_catalog,
    generic_question_examples,
    preferred_category_column,
    prepare_table_for_analysis,
)

__all__ = [
    "AggregationSpec",
    "apply_column_corrections",
    "AmbiguousQuestionError",
    "ask_generic_table_question",
    "build_chart_data",
    "build_generic_semantic_catalog",
    "DimensionSemantic",
    "FilterSpec",
    "generic_question_examples",
    "NoMatchingRowsError",
    "MetricSemantic",
    "NaturalLanguageQueryResult",
    "NaturalLanguageTableAgent",
    "QuestionInterpretation",
    "QuestionInterpretationError",
    "QueryExecutionError",
    "QueryRequest",
    "QueryResult",
    "SortSpec",
    "SemanticCatalog",
    "TableQueryAgent",
    "TotalExclusion",
    "UnknownColumnError",
    "UnknownTableError",
    "UnsupportedQuestionError",
    "execute_query",
    "interpret_question",
    "parse_query_request",
    "preferred_category_column",
    "prepare_table_for_analysis",
]
